# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = C:\msys64\mingw64\bin\cmake.exe

# The command to remove a file.
RM = C:\msys64\mingw64\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\backup\Pictures\NoveoCPP-main

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\backup\Pictures\NoveoCPP-main

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	C:\msys64\mingw64\bin\cmake.exe -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	C:\msys64\mingw64\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\backup\Pictures\NoveoCPP-main\CMakeFiles C:\Users\backup\Pictures\NoveoCPP-main\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\backup\Pictures\NoveoCPP-main\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named NoveoDesktop

# Build rule for target.
NoveoDesktop: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 NoveoDesktop
.PHONY : NoveoDesktop

# fast build rule for target.
NoveoDesktop/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\NoveoDesktop.dir\build.make CMakeFiles/NoveoDesktop.dir/build
.PHONY : NoveoDesktop/fast

#=============================================================================
# Target rules for targets named NoveoDesktop_autogen_timestamp_deps

# Build rule for target.
NoveoDesktop_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 NoveoDesktop_autogen_timestamp_deps
.PHONY : NoveoDesktop_autogen_timestamp_deps

# fast build rule for target.
NoveoDesktop_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\NoveoDesktop_autogen_timestamp_deps.dir\build.make CMakeFiles/NoveoDesktop_autogen_timestamp_deps.dir/build
.PHONY : NoveoDesktop_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named NoveoDesktop_autogen

# Build rule for target.
NoveoDesktop_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 NoveoDesktop_autogen
.PHONY : NoveoDesktop_autogen

# fast build rule for target.
NoveoDesktop_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\NoveoDesktop_autogen.dir\build.make CMakeFiles/NoveoDesktop_autogen.dir/build
.PHONY : NoveoDesktop_autogen/fast

MainWindow.obj: MainWindow.cpp.obj
.PHONY : MainWindow.obj

# target to build an object file
MainWindow.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\NoveoDesktop.dir\build.make CMakeFiles/NoveoDesktop.dir/MainWindow.cpp.obj
.PHONY : MainWindow.cpp.obj

MainWindow.i: MainWindow.cpp.i
.PHONY : MainWindow.i

# target to preprocess a source file
MainWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\NoveoDesktop.dir\build.make CMakeFiles/NoveoDesktop.dir/MainWindow.cpp.i
.PHONY : MainWindow.cpp.i

MainWindow.s: MainWindow.cpp.s
.PHONY : MainWindow.s

# target to generate assembly for a file
MainWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\NoveoDesktop.dir\build.make CMakeFiles/NoveoDesktop.dir/MainWindow.cpp.s
.PHONY : MainWindow.cpp.s

MessageBubble.obj: MessageBubble.cpp.obj
.PHONY : MessageBubble.obj

# target to build an object file
MessageBubble.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\NoveoDesktop.dir\build.make CMakeFiles/NoveoDesktop.dir/MessageBubble.cpp.obj
.PHONY : MessageBubble.cpp.obj

MessageBubble.i: MessageBubble.cpp.i
.PHONY : MessageBubble.i

# target to preprocess a source file
MessageBubble.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\NoveoDesktop.dir\build.make CMakeFiles/NoveoDesktop.dir/MessageBubble.cpp.i
.PHONY : MessageBubble.cpp.i

MessageBubble.s: MessageBubble.cpp.s
.PHONY : MessageBubble.s

# target to generate assembly for a file
MessageBubble.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\NoveoDesktop.dir\build.make CMakeFiles/NoveoDesktop.dir/MessageBubble.cpp.s
.PHONY : MessageBubble.cpp.s

NoveoDesktop_autogen/mocs_compilation.obj: NoveoDesktop_autogen/mocs_compilation.cpp.obj
.PHONY : NoveoDesktop_autogen/mocs_compilation.obj

# target to build an object file
NoveoDesktop_autogen/mocs_compilation.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\NoveoDesktop.dir\build.make CMakeFiles/NoveoDesktop.dir/NoveoDesktop_autogen/mocs_compilation.cpp.obj
.PHONY : NoveoDesktop_autogen/mocs_compilation.cpp.obj

NoveoDesktop_autogen/mocs_compilation.i: NoveoDesktop_autogen/mocs_compilation.cpp.i
.PHONY : NoveoDesktop_autogen/mocs_compilation.i

# target to preprocess a source file
NoveoDesktop_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\NoveoDesktop.dir\build.make CMakeFiles/NoveoDesktop.dir/NoveoDesktop_autogen/mocs_compilation.cpp.i
.PHONY : NoveoDesktop_autogen/mocs_compilation.cpp.i

NoveoDesktop_autogen/mocs_compilation.s: NoveoDesktop_autogen/mocs_compilation.cpp.s
.PHONY : NoveoDesktop_autogen/mocs_compilation.s

# target to generate assembly for a file
NoveoDesktop_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\NoveoDesktop.dir\build.make CMakeFiles/NoveoDesktop.dir/NoveoDesktop_autogen/mocs_compilation.cpp.s
.PHONY : NoveoDesktop_autogen/mocs_compilation.cpp.s

WebSocketClient.obj: WebSocketClient.cpp.obj
.PHONY : WebSocketClient.obj

# target to build an object file
WebSocketClient.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\NoveoDesktop.dir\build.make CMakeFiles/NoveoDesktop.dir/WebSocketClient.cpp.obj
.PHONY : WebSocketClient.cpp.obj

WebSocketClient.i: WebSocketClient.cpp.i
.PHONY : WebSocketClient.i

# target to preprocess a source file
WebSocketClient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\NoveoDesktop.dir\build.make CMakeFiles/NoveoDesktop.dir/WebSocketClient.cpp.i
.PHONY : WebSocketClient.cpp.i

WebSocketClient.s: WebSocketClient.cpp.s
.PHONY : WebSocketClient.s

# target to generate assembly for a file
WebSocketClient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\NoveoDesktop.dir\build.make CMakeFiles/NoveoDesktop.dir/WebSocketClient.cpp.s
.PHONY : WebSocketClient.cpp.s

main.obj: main.cpp.obj
.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\NoveoDesktop.dir\build.make CMakeFiles/NoveoDesktop.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\NoveoDesktop.dir\build.make CMakeFiles/NoveoDesktop.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\NoveoDesktop.dir\build.make CMakeFiles/NoveoDesktop.dir/main.cpp.s
.PHONY : main.cpp.s

version.obj: version.rc.obj
.PHONY : version.obj

# target to build an object file
version.rc.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\NoveoDesktop.dir\build.make CMakeFiles/NoveoDesktop.dir/version.rc.obj
.PHONY : version.rc.obj

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... NoveoDesktop_autogen
	@echo ... NoveoDesktop_autogen_timestamp_deps
	@echo ... NoveoDesktop
	@echo ... MainWindow.obj
	@echo ... MainWindow.i
	@echo ... MainWindow.s
	@echo ... MessageBubble.obj
	@echo ... MessageBubble.i
	@echo ... MessageBubble.s
	@echo ... NoveoDesktop_autogen/mocs_compilation.obj
	@echo ... NoveoDesktop_autogen/mocs_compilation.i
	@echo ... NoveoDesktop_autogen/mocs_compilation.s
	@echo ... WebSocketClient.obj
	@echo ... WebSocketClient.i
	@echo ... WebSocketClient.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
	@echo ... version.obj
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

